export const ShopActionTypes = {
    UPDATE_COLLECTION_ITEMS: 'UPDATE_COLLECTION_ITEMS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_START :'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_SUCCESS'
}